name = "nexus-marketplace-api"
main = "src/index.js"
compatibility_date = "2024-11-01"

[vars]
API_VERSION = "v1"

[[d1_databases]]
binding = "DB"
database_name = "nexus-marketplace"
database_id = "0393dd1c-bcc3-4b03-aa3e-008ed44eff77"

[ai]
binding = "AI"

[[vectorize]]
binding = "VECTORIZE"
index_name = "nexus-card-embeddings"
